# This is a basic workflow to help you get started with Actions
name: Pushes to ICEI/TCC repository

on:
  push:
    branches:
      - master
  
jobs: 
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Push to TCC
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: ICEI-PUC-Minas-PPLES-TI/plf-es-2022-1-tcci-5308100-pes-gabriel-chaves-ian-bittencourt
